// swift-tools-version:6.0

// Pizzini Swift Package — wraps the Rust crypto-core via XCFramework
// and the vendored SQLCipher amalgamation.
//
// Before opening the iOS app in Xcode, run `scripts/build-xcframework.sh`
// to produce build/PizziniCryptoCore.xcframework. The Xcode project then
// adds this package as a local dependency:
//   File → Add Package Dependencies → Add Local… → select the workspace root.
//
// Products:
//   PizziniCryptoCoreFFI    — raw C ABI (auto-generated by cbindgen).
//   PizziniCryptoCore       — idiomatic Swift wrapper. Prefer this from app code.
//   PizziniSQLCipher        — vendored SQLCipher amalgamation (C). Internal
//                             dependency of PizziniDB; the iOS app target
//                             should not import this directly.
//   PizziniDB               — thin typed wrapper around SQLCipher (connection /
//                             statement / transaction lifecycle). The app
//                             target imports this to talk to the encrypted db.

import PackageDescription

let package = Package(
    name: "PizziniCryptoCore",
    platforms: [.iOS(.v18)],
    products: [
        .library(name: "PizziniCryptoCore", targets: ["PizziniCryptoCore"]),
        .library(name: "PizziniDB", targets: ["PizziniDB"]),
    ],
    targets: [
        .binaryTarget(
            name: "PizziniCryptoCoreFFI",
            path: "build/PizziniCryptoCore.xcframework"
        ),
        .target(
            name: "PizziniCryptoCore",
            dependencies: ["PizziniCryptoCoreFFI"],
            path: "swift/Sources/PizziniCryptoCore"
        ),
        // SQLCipher amalgamation, vendored under
        // `swift/Sources/PizziniSQLCipher/`. Regenerate via
        // `scripts/build-sqlcipher-amalgamation.sh` when bumping the
        // upstream tag. Compile flags:
        //   SQLITE_HAS_CODEC       enables SQLCipher's encryption hook
        //   SQLCIPHER_CRYPTO_CC    uses Apple CommonCrypto (no OpenSSL)
        //   SQLITE_TEMP_STORE=2    keep temp data in memory only —
        //                          a temp file on disk would defeat
        //                          encryption-at-rest for transient
        //                          query state.
        //   SQLITE_THREADSAFE=1    serialized mode; pairs with the
        //                          single-queue DB owner in PizziniDB.
        //   SQLITE_DEFAULT_MEMSTATUS=0  small perf win, no impact
        //                          on correctness.
        //   NDEBUG=1               disables sqlite's runtime asserts
        //                          (we trust the amalgamation; assert
        //                          overhead is in the hot path).
        //   HAVE_USLEEP=1          iOS has usleep — without this the
        //                          busy-wait fallback is a ~1s sleep
        //                          rather than the configurable
        //                          microsecond one.
        //   SQLITE_OS_UNIX=1       iOS uses the unix VFS, not winnt.
        .target(
            name: "PizziniSQLCipher",
            path: "swift/Sources/PizziniSQLCipher",
            exclude: ["VERSION"],
            sources: ["pizzini_sqlcipher.c"],
            publicHeadersPath: "include",
            cSettings: [
                .define("SQLITE_HAS_CODEC"),
                .define("SQLCIPHER_CRYPTO_CC"),
                .define("SQLITE_TEMP_STORE", to: "2"),
                .define("SQLITE_THREADSAFE", to: "1"),
                .define("SQLITE_DEFAULT_MEMSTATUS", to: "0"),
                .define("NDEBUG", to: "1"),
                .define("HAVE_USLEEP", to: "1"),
                .define("SQLITE_OS_UNIX", to: "1"),
            ]
        ),
        .target(
            name: "PizziniDB",
            dependencies: ["PizziniSQLCipher"],
            path: "swift/Sources/PizziniDB"
        ),
        .testTarget(
            name: "PizziniCryptoCoreTests",
            dependencies: ["PizziniCryptoCore"],
            path: "swift/Tests/PizziniCryptoCoreTests"
        ),
        .testTarget(
            name: "PizziniDBTests",
            dependencies: ["PizziniDB"],
            path: "swift/Tests/PizziniDBTests"
        ),
    ]
)
