// swift-tools-version:6.0

// Pizzini Swift Package — wraps the Rust crypto-core via XCFramework.
//
// Before opening the iOS app in Xcode, run `scripts/build-xcframework.sh`
// to produce build/PizziniCryptoCore.xcframework. The Xcode project then
// adds this package as a local dependency:
//   File → Add Package Dependencies → Add Local… → select the workspace root.
//
// Two products:
//   PizziniCryptoCoreFFI    — raw C ABI (auto-generated by cbindgen).
//   PizziniCryptoCore       — idiomatic Swift wrapper. Prefer this from app code.

import PackageDescription

let package = Package(
    name: "PizziniCryptoCore",
    platforms: [.iOS(.v18)],
    products: [
        .library(name: "PizziniCryptoCore", targets: ["PizziniCryptoCore"]),
    ],
    targets: [
        .binaryTarget(
            name: "PizziniCryptoCoreFFI",
            path: "build/PizziniCryptoCore.xcframework"
        ),
        .target(
            name: "PizziniCryptoCore",
            dependencies: ["PizziniCryptoCoreFFI"],
            path: "swift/Sources/PizziniCryptoCore"
        ),
        .testTarget(
            name: "PizziniCryptoCoreTests",
            dependencies: ["PizziniCryptoCore"],
            path: "swift/Tests/PizziniCryptoCoreTests"
        ),
    ]
)
