#!/usr/bin/env bash
# Build the SQLCipher amalgamation (`sqlcipher.c` + `sqlcipher.h`) and
# vendor it under `swift/Sources/PizziniSQLCipher/`. Run once per
# SQLCipher version bump; the output files are committed and consumed
# directly by SwiftPM. Builds reproducibly from the pinned upstream
# tag without depending on a network fetch at compile time.
#
# Requirements: tclsh, make, a C compiler.
#
# Usage:  scripts/build-sqlcipher-amalgamation.sh
# Bump:   set SQLCIPHER_TAG below, rerun the script, commit the result.
#
# Why we vendor: SQLCipher Community is BSD-style (AGPL-compatible),
# the amalgamation is a single ~9 MB `.c` file that's fully auditable,
# and bundling it removes a build-time network dependency from
# every developer + CI machine.

set -euo pipefail

# Pinned upstream tag. Current stable as of 2026-05: v4.6.1.
# Bump deliberately — every bump is a re-audit of the C source.
SQLCIPHER_TAG="${SQLCIPHER_TAG:-v4.6.1}"
SQLCIPHER_GIT="${SQLCIPHER_GIT:-https://github.com/sqlcipher/sqlcipher.git}"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$REPO_ROOT/swift/Sources/PizziniSQLCipher"
WORK_DIR="$(mktemp -d -t pizzini-sqlcipher.XXXXXX)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "==> SQLCipher $SQLCIPHER_TAG → $OUT_DIR"

git clone --depth 1 --branch "$SQLCIPHER_TAG" "$SQLCIPHER_GIT" "$WORK_DIR/src"

cd "$WORK_DIR/src"

# CommonCrypto on Apple platforms — no OpenSSL link, no separate
# dependency at runtime. SQLCipher's `--with-crypto-lib=commoncrypto`
# wires the build to use Apple's libCommonCrypto.dylib (system
# framework, always available on iOS).
#
# `--disable-tcl` disables building SQLCipher's Tcl *bindings* — we
# still need tclsh to GENERATE the amalgamation but we don't need to
# ship the Tcl shell extension into the iOS binary.
./configure \
    --with-crypto-lib=commoncrypto \
    --disable-tcl \
    --enable-tempstore=yes \
    >/dev/null

# Generate the amalgamation. `sqlite3.c` is the single-file SQLite +
# SQLCipher source; `sqlite3.h` is the matching header.
make sqlite3.c >/dev/null

mkdir -p "$OUT_DIR/include"

# Rename to `pizzini_sqlcipher.{c,h}` so it can't be confused with a
# system `sqlite3.h` by an unrelated import elsewhere in the project,
# and so the SwiftPM C target picks it up unambiguously.
cp sqlite3.c "$OUT_DIR/pizzini_sqlcipher.c"
cp sqlite3.h "$OUT_DIR/include/pizzini_sqlcipher.h"

# A separate header that re-exports the SQLite C ABI under our
# umbrella name keeps the include directive in Swift's
# `module.modulemap` stable across SQLCipher upgrades.
cat >"$OUT_DIR/include/PizziniSQLCipher.h" <<EOF
/* SPDX-License-Identifier: AGPL-3.0-or-later
 * Umbrella header for the vendored SQLCipher amalgamation. Auto-
 * generated by scripts/build-sqlcipher-amalgamation.sh — do not edit
 * by hand. Bump SQLCIPHER_TAG in the script and rerun.
 *
 * Upstream: $SQLCIPHER_GIT @ $SQLCIPHER_TAG
 */
#ifndef PIZZINI_SQLCIPHER_UMBRELLA_H
#define PIZZINI_SQLCIPHER_UMBRELLA_H

#include "pizzini_sqlcipher.h"

#endif
EOF

# Module map so Swift code can `import PizziniSQLCipher` and call
# `sqlite3_open_v2`, `sqlite3_key_v2`, etc. directly.
cat >"$OUT_DIR/include/module.modulemap" <<'EOF'
module PizziniSQLCipher [system] {
    umbrella header "PizziniSQLCipher.h"
    link "z"
    export *
}
EOF

# Stamp the version we vendored so reviewers can diff against
# upstream without rerunning git log.
echo "$SQLCIPHER_TAG" > "$OUT_DIR/VERSION"

echo "==> Done. Vendored:"
ls -la "$OUT_DIR"
ls -la "$OUT_DIR/include"
