/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef PIZZINI_CRYPTO_CORE_H
#define PIZZINI_CRYPTO_CORE_H

#include <stdint.h>
#include <stddef.h>

#define PIZZINI_OK 0

#define PIZZINI_ERR_INVALID_ARG -1

#define PIZZINI_ERR_BUFFER_TOO_SMALL -2

#define PIZZINI_ERR_INTERNAL -3

#define PIZZINI_MSG_TYPE_PREKEY 0

#define PIZZINI_MSG_TYPE_WHISPER 1

/**
 * libsignal-native public-key wire size: 1-byte DJB type prefix + 32-byte
 * Curve25519 point. The bundle field carries exactly this many bytes;
 * rejecting other sizes keeps the relay's per-recipient verify-key table
 * predictable, and any future migration to a different curve flavour
 * will trip the size check loudly instead of silently mis-verifying.
 */
#define DELIVERY_TOKEN_VERIFY_KEY_LEN 33

typedef struct DeviceStore DeviceStore;

/**
 * Returns a static null-terminated UTF-8 string with the crate version.
 * The pointer is valid for the lifetime of the process; do not free.
 */
const char *pizzini_crypto_core_version(void);

/**
 * Generates a fresh long-term identity keypair (libsignal IdentityKeyPair) and
 * writes its serialized form into `out_buf`.
 *
 * On success returns `PIZZINI_OK` and `*out_len` is the number of bytes written.
 * If `out_buf_cap` is smaller than required, returns `PIZZINI_ERR_BUFFER_TOO_SMALL`
 * and `*out_len` is the required size — caller can retry with a larger buffer.
 *
 * # Safety
 * - `out_buf` must point to at least `out_buf_cap` writable bytes.
 * - `out_len` must point to a valid `usize`.
 */
int32_t pizzini_identity_keypair_generate(uint8_t *out_buf,
                                          uintptr_t out_buf_cap,
                                          uintptr_t *out_len);

/**
 * Creates a new device store.
 *
 * If `seed_ptr` is null, a fresh identity keypair is generated. Otherwise
 * `(seed_ptr, seed_len)` must be the bytes returned by a prior
 * `pizzini_store_identity_keypair` call (libsignal's serialized
 * IdentityKeyPair) — used to rehydrate an identity from Keychain. This
 * path keeps the identity but loses session/prekey state. For full
 * continuity (sessions, ratchet) use `pizzini_store_new_from_serialized`.
 *
 * Returns a non-null opaque handle on success, null on failure.
 *
 * # Safety
 * `seed_ptr` must either be null or point to `seed_len` readable bytes.
 */
struct DeviceStore *pizzini_store_new(const uint8_t *seed_ptr, uintptr_t seed_len);

/**
 * Creates a device store from a full serialized snapshot (the bytes
 * returned by `pizzini_store_serialize`). Restores identity, registration
 * id, prekeys, signed prekeys, kyber prekeys, and per-peer session state.
 *
 * Returns null if the blob is malformed.
 *
 * # Safety
 * `bytes` must point to `len` readable bytes.
 */
struct DeviceStore *pizzini_store_new_from_serialized(const uint8_t *bytes, uintptr_t len);

/**
 * Releases a device-store handle. Safe to call with null.
 *
 * # Safety
 * `store` must be a pointer previously returned by `pizzini_store_new` and
 * not yet freed.
 */
void pizzini_store_free(struct DeviceStore *store);

/**
 * Writes the serialized `IdentityKeyPair` (private + public) to `out_buf`.
 * Persist these bytes in the Keychain; pass them back to `pizzini_store_new`
 * on the next launch.
 *
 * # Safety
 * `store` must be a live handle. `out_buf` must point to `out_buf_cap`
 * writable bytes; `out_len` must point to a valid `usize`.
 */
int32_t pizzini_store_identity_keypair(struct DeviceStore *store,
                                       uint8_t *out_buf,
                                       uintptr_t out_buf_cap,
                                       uintptr_t *out_len);

/**
 * Writes the 33-byte serialized public IdentityKey. This is the routable
 * peer-id used for transport addressing and ProtocolAddress naming.
 *
 * # Safety
 * Same as `pizzini_store_identity_keypair`.
 */
int32_t pizzini_store_identity_public(struct DeviceStore *store,
                                      uint8_t *out_buf,
                                      uintptr_t out_buf_cap,
                                      uintptr_t *out_len);

/**
 * Generates a fresh PreKey bundle (rotates one-time, signed, and Kyber
 * pre-keys), persists them in the store, and writes the wire-format bytes.
 * See `store.rs` for the format. Hand to a peer over QR / pairing.
 *
 * # Safety
 * Same as `pizzini_store_identity_keypair`.
 */
int32_t pizzini_store_publish_bundle(struct DeviceStore *store,
                                     uint8_t *out_buf,
                                     uintptr_t out_buf_cap,
                                     uintptr_t *out_len);

/**
 * Processes a peer's PreKey bundle (PQXDH handshake) and stores the
 * resulting session keyed by `peer_identity` (the peer's 33-byte
 * IdentityKey bytes). After this returns OK, encrypt/decrypt may be called.
 *
 * # Safety
 * All pointers must be non-null and describe valid slices.
 */
int32_t pizzini_store_initiate_session(struct DeviceStore *store,
                                       const uint8_t *peer_identity,
                                       uintptr_t peer_identity_len,
                                       const uint8_t *bundle,
                                       uintptr_t bundle_len);

/**
 * Encrypts `plaintext` for `peer_identity`. Writes the wire ciphertext to
 * `out_ciphertext` and the message type tag to `out_message_type`.
 *
 * # Safety
 * All pointers must be non-null and point to memory of the declared sizes.
 */
int32_t pizzini_store_encrypt(struct DeviceStore *store,
                              const uint8_t *peer_identity,
                              uintptr_t peer_identity_len,
                              const uint8_t *plaintext,
                              uintptr_t plaintext_len,
                              uint8_t *out_ciphertext,
                              uintptr_t out_ciphertext_cap,
                              uintptr_t *out_ciphertext_len,
                              uint32_t *out_message_type);

/**
 * Decrypts a wire ciphertext from `peer_identity`. `is_prekey` selects
 * PreKey vs Whisper parsing — the caller must communicate this out-of-band
 * (we ship it as a wire-protocol tag, not embedded in the ciphertext).
 *
 * # Safety
 * All pointers must be non-null and point to memory of the declared sizes.
 */
int32_t pizzini_store_decrypt(struct DeviceStore *store,
                              const uint8_t *peer_identity,
                              uintptr_t peer_identity_len,
                              const uint8_t *ciphertext,
                              uintptr_t ciphertext_len,
                              uint32_t is_prekey,
                              uint8_t *out_plaintext,
                              uintptr_t out_plaintext_cap,
                              uintptr_t *out_plaintext_len);

/**
 * Snapshot the entire store (identity + prekeys + sessions) to a versioned
 * binary blob. Persist this in Keychain or SQLCipher; pass it back to
 * `pizzini_store_new_from_serialized` on the next launch.
 *
 * # Safety
 * `store` must be a live handle. `out_buf`/`out_len` as for the other
 * blob-returning calls.
 */
int32_t pizzini_store_serialize(struct DeviceStore *store,
                                uint8_t *out_buf,
                                uintptr_t out_buf_cap,
                                uintptr_t *out_len);

/**
 * Idempotently track an identity_pub. Called by the host right after
 * scanning a peer's QR — pre-seeds the peer so it survives serialize even
 * before the actual session handshake completes.
 *
 * # Safety
 * `store` must be a live handle. `peer_identity` must point to
 * `peer_identity_len` readable bytes.
 */
int32_t pizzini_store_register_peer(struct DeviceStore *store,
                                    const uint8_t *peer_identity,
                                    uintptr_t peer_identity_len);

/**
 * Drop a peer: forget the libsignal session and remove it from the
 * serialize index. After this call, encrypting to or decrypting from the
 * peer requires re-running PQXDH from a fresh bundle.
 *
 * # Safety
 * Same as `pizzini_store_register_peer`.
 */
int32_t pizzini_store_forget_peer(struct DeviceStore *store,
                                  const uint8_t *peer_identity,
                                  uintptr_t peer_identity_len);

/**
 * Writes the recipient's published delivery-token verify key (33 bytes:
 * libsignal PublicKey serialize() — 1-byte type prefix + 32-byte point).
 * Used by the relay-side token check; deterministic per IdentityKeyPair.
 *
 * # Safety
 * Same as `pizzini_store_identity_keypair`.
 */
int32_t pizzini_store_delivery_token_verify_key(struct DeviceStore *store,
                                                uint8_t *out_buf,
                                                uintptr_t out_buf_cap,
                                                uintptr_t *out_len);

/**
 * Mints (or refreshes) the cached SenderCertificate and writes its wire
 * bytes. Production callers reach `pizzini_store_seal_send` directly
 * which calls this internally; this entry point is exposed mostly for
 * debug/logging in Swift.
 *
 * # Safety
 * Same as `pizzini_store_publish_bundle`.
 */
int32_t pizzini_store_ensure_sender_certificate(struct DeviceStore *store,
                                                uint8_t *out_buf,
                                                uintptr_t out_buf_cap,
                                                uintptr_t *out_len);

/**
 * Sealed-sender SEND. Wraps `plaintext` in a libsignal ratchet
 * ciphertext, prefixes the 16-byte `message_id` and 1-byte `is_prekey`
 * at the USMC layer, seals to `peer_identity_pub`, and writes the wire
 * bytes the relay forwards verbatim. Mints the SenderCertificate
 * internally if absent.
 *
 * # Safety
 * All non-null pointers must describe valid slices of the declared sizes.
 * `message_id` must point to exactly 16 readable bytes.
 */
int32_t pizzini_store_seal_send(struct DeviceStore *store,
                                const uint8_t *peer_identity,
                                uintptr_t peer_identity_len,
                                const uint8_t *message_id_16,
                                const uint8_t *plaintext,
                                uintptr_t plaintext_len,
                                uint8_t *out_sealed,
                                uintptr_t out_sealed_cap,
                                uintptr_t *out_sealed_len);

/**
 * Sealed-sender RECEIVE. Validates the embedded cert against the
 * claimed sender's identity_pub (looked up in the store's peers list),
 * decrypts the inner ratchet ciphertext, and writes three outputs:
 *
 * - `out_sender` — the sender's 33-byte identity_pub.
 * - `out_message_id_16` — the 16-byte message_id from the USMC header.
 * - `out_plaintext` — the inner plaintext bytes.
 *
 * Returns `PIZZINI_ERR_BUFFER_TOO_SMALL` when EITHER `out_sender` or
 * `out_plaintext` is too small to receive its payload, with the
 * corresponding `*_len` filled in. Caller retries with both buffers
 * sized appropriately. (We don't surface partial success — the
 * alternative is "decrypted, then refused to copy", which leaves the
 * ratchet advanced but the caller empty-handed.)
 *
 * # Safety
 * All non-null pointers must describe valid slices of the declared sizes.
 * `out_message_id_16` must point to 16 writable bytes.
 */
int32_t pizzini_store_seal_receive(struct DeviceStore *store,
                                   const uint8_t *sealed,
                                   uintptr_t sealed_len,
                                   uint8_t *out_sender,
                                   uintptr_t out_sender_cap,
                                   uintptr_t *out_sender_len,
                                   uint8_t *out_message_id_16,
                                   uint8_t *out_plaintext,
                                   uintptr_t out_plaintext_cap,
                                   uintptr_t *out_plaintext_len);

#endif  /* PIZZINI_CRYPTO_CORE_H */
