/* SPDX-License-Identifier: AGPL-3.0-or-later */
/* Auto-generated by cbindgen — do not edit by hand. */

#ifndef PIZZINI_CRYPTO_CORE_H
#define PIZZINI_CRYPTO_CORE_H

#include <stdint.h>
#include <stddef.h>

#define PIZZINI_OK 0

#define PIZZINI_ERR_INVALID_ARG -1

#define PIZZINI_ERR_BUFFER_TOO_SMALL -2

#define PIZZINI_ERR_INTERNAL -3

#define PIZZINI_MSG_TYPE_PREKEY 0

#define PIZZINI_MSG_TYPE_WHISPER 1

typedef struct DeviceStore DeviceStore;

typedef struct LoopbackState LoopbackState;

/**
 * Returns a static null-terminated UTF-8 string with the crate version.
 * The pointer is valid for the lifetime of the process; do not free.
 */
const char *pizzini_crypto_core_version(void);

/**
 * Generates a fresh long-term identity keypair (libsignal IdentityKeyPair) and
 * writes its serialized form into `out_buf`.
 *
 * On success returns `PIZZINI_OK` and `*out_len` is the number of bytes written.
 * If `out_buf_cap` is smaller than required, returns `PIZZINI_ERR_BUFFER_TOO_SMALL`
 * and `*out_len` is the required size — caller can retry with a larger buffer.
 *
 * # Safety
 * - `out_buf` must point to at least `out_buf_cap` writable bytes.
 * - `out_len` must point to a valid `usize`.
 */
int32_t pizzini_identity_keypair_generate(uint8_t *out_buf,
                                          uintptr_t out_buf_cap,
                                          uintptr_t *out_len);

/**
 * Creates a new in-process loopback session. Returns a non-null opaque
 * handle, or null on internal error. Caller must release with
 * `pizzini_loopback_free`.
 */
struct LoopbackState *pizzini_loopback_new(void);

/**
 * Releases a loopback handle. Safe to call with null.
 *
 * # Safety
 * `state` must be a pointer previously returned by `pizzini_loopback_new`,
 * and not yet freed. Passing any other pointer is undefined behavior.
 */
void pizzini_loopback_free(struct LoopbackState *state);

/**
 * Sends `plaintext` from Alice to Bob: encrypts, decrypts, and returns both
 * the wire-format ciphertext and Bob's recovered plaintext along with the
 * CiphertextMessageType (PIZZINI_MSG_TYPE_PREKEY or _WHISPER).
 *
 * On `PIZZINI_ERR_BUFFER_TOO_SMALL`, the corresponding `*out_len` is set to
 * the required size; the other output's `*out_len` is unspecified. Caller
 * should retry with a buffer at least that large. Recommended caps:
 *   - ciphertext: 4096 bytes (covers Kyber1024 PreKey messages comfortably)
 *   - decrypted:  plaintext_len + 256
 *
 * # Safety
 * All pointers must be non-null and point to memory of the declared sizes.
 * `state` must be a live handle from `pizzini_loopback_new`.
 */
int32_t pizzini_loopback_alice_send(struct LoopbackState *state,
                                    const uint8_t *plaintext,
                                    uintptr_t plaintext_len,
                                    uint8_t *out_ciphertext,
                                    uintptr_t out_ciphertext_cap,
                                    uintptr_t *out_ciphertext_len,
                                    uint8_t *out_decrypted,
                                    uintptr_t out_decrypted_cap,
                                    uintptr_t *out_decrypted_len,
                                    uint32_t *out_message_type);

/**
 * Sends `plaintext` from Bob to Alice. Mirror of `pizzini_loopback_alice_send`.
 *
 * # Safety
 * Same as `pizzini_loopback_alice_send`.
 */
int32_t pizzini_loopback_bob_send(struct LoopbackState *state,
                                  const uint8_t *plaintext,
                                  uintptr_t plaintext_len,
                                  uint8_t *out_ciphertext,
                                  uintptr_t out_ciphertext_cap,
                                  uintptr_t *out_ciphertext_len,
                                  uint8_t *out_decrypted,
                                  uintptr_t out_decrypted_cap,
                                  uintptr_t *out_decrypted_len,
                                  uint32_t *out_message_type);

/**
 * Creates a new device store.
 *
 * If `seed_ptr` is null, a fresh identity keypair is generated. Otherwise
 * `(seed_ptr, seed_len)` must be the bytes returned by a prior
 * `pizzini_store_identity_keypair` call (libsignal's serialized
 * IdentityKeyPair) — used to rehydrate an identity from Keychain.
 *
 * Returns a non-null opaque handle on success, null on failure.
 *
 * # Safety
 * `seed_ptr` must either be null or point to `seed_len` readable bytes.
 */
struct DeviceStore *pizzini_store_new(const uint8_t *seed_ptr, uintptr_t seed_len);

/**
 * Releases a device-store handle. Safe to call with null.
 *
 * # Safety
 * `store` must be a pointer previously returned by `pizzini_store_new` and
 * not yet freed.
 */
void pizzini_store_free(struct DeviceStore *store);

/**
 * Writes the serialized `IdentityKeyPair` (private + public) to `out_buf`.
 * Persist these bytes in the Keychain; pass them back to `pizzini_store_new`
 * on the next launch.
 *
 * # Safety
 * `store` must be a live handle. `out_buf` must point to `out_buf_cap`
 * writable bytes; `out_len` must point to a valid `usize`.
 */
int32_t pizzini_store_identity_keypair(struct DeviceStore *store,
                                       uint8_t *out_buf,
                                       uintptr_t out_buf_cap,
                                       uintptr_t *out_len);

/**
 * Writes the 33-byte serialized public IdentityKey. This is the routable
 * peer-id used for transport addressing and ProtocolAddress naming.
 *
 * # Safety
 * Same as `pizzini_store_identity_keypair`.
 */
int32_t pizzini_store_identity_public(struct DeviceStore *store,
                                      uint8_t *out_buf,
                                      uintptr_t out_buf_cap,
                                      uintptr_t *out_len);

/**
 * Generates a fresh PreKey bundle (rotates one-time, signed, and Kyber
 * pre-keys), persists them in the store, and writes the wire-format bytes.
 * See `store.rs` for the format. Hand to a peer over QR / pairing.
 *
 * # Safety
 * Same as `pizzini_store_identity_keypair`.
 */
int32_t pizzini_store_publish_bundle(struct DeviceStore *store,
                                     uint8_t *out_buf,
                                     uintptr_t out_buf_cap,
                                     uintptr_t *out_len);

/**
 * Processes a peer's PreKey bundle (PQXDH handshake) and stores the
 * resulting session keyed by `peer_identity` (the peer's 33-byte
 * IdentityKey bytes). After this returns OK, encrypt/decrypt may be called.
 *
 * # Safety
 * All pointers must be non-null and describe valid slices.
 */
int32_t pizzini_store_initiate_session(struct DeviceStore *store,
                                       const uint8_t *peer_identity,
                                       uintptr_t peer_identity_len,
                                       const uint8_t *bundle,
                                       uintptr_t bundle_len);

/**
 * Encrypts `plaintext` for `peer_identity`. Writes the wire ciphertext to
 * `out_ciphertext` and the message type tag to `out_message_type`.
 *
 * # Safety
 * All pointers must be non-null and point to memory of the declared sizes.
 */
int32_t pizzini_store_encrypt(struct DeviceStore *store,
                              const uint8_t *peer_identity,
                              uintptr_t peer_identity_len,
                              const uint8_t *plaintext,
                              uintptr_t plaintext_len,
                              uint8_t *out_ciphertext,
                              uintptr_t out_ciphertext_cap,
                              uintptr_t *out_ciphertext_len,
                              uint32_t *out_message_type);

/**
 * Decrypts a wire ciphertext from `peer_identity`. `is_prekey` selects
 * PreKey vs Whisper parsing — the caller must communicate this out-of-band
 * (we ship it as a wire-protocol tag, not embedded in the ciphertext).
 *
 * # Safety
 * All pointers must be non-null and point to memory of the declared sizes.
 */
int32_t pizzini_store_decrypt(struct DeviceStore *store,
                              const uint8_t *peer_identity,
                              uintptr_t peer_identity_len,
                              const uint8_t *ciphertext,
                              uintptr_t ciphertext_len,
                              uint32_t is_prekey,
                              uint8_t *out_plaintext,
                              uintptr_t out_plaintext_cap,
                              uintptr_t *out_plaintext_len);

#endif  /* PIZZINI_CRYPTO_CORE_H */
