/* SPDX-License-Identifier: AGPL-3.0-or-later
 * Umbrella header for the vendored SQLCipher amalgamation.
 *
 * The SQLCipher-only API surface (`sqlite3_key`, `sqlite3_key_v2`,
 * `sqlite3_rekey`, etc.) is gated behind `SQLITE_HAS_CODEC` inside
 * pizzini_sqlcipher.h. SwiftPM's `cSettings.define` only affects the
 * `.c` compilation, not the header import that Swift module
 * synthesis performs — so we define the same flag here, BEFORE the
 * include, to make sure both the C compilation and the Swift module
 * see the same API surface.
 *
 * Upstream tracked in `VERSION` (one-line tag) and regenerated by
 * `scripts/build-sqlcipher-amalgamation.sh`.
 */
#ifndef PIZZINI_SQLCIPHER_UMBRELLA_H
#define PIZZINI_SQLCIPHER_UMBRELLA_H

#ifndef SQLITE_HAS_CODEC
#define SQLITE_HAS_CODEC 1
#endif

#include "pizzini_sqlcipher.h"

#endif
